name: Build wxapp library

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: 'Install dependencies'
      run: npm install
    - name: 'Building'
      run: sh build/deploy/script.sh
    - name: 'Get current date'
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: 'Upload artifact'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.date.outputs.date }}-lib-wx
        path: lib/wx